services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  
  web:
    build: .
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      DB_DB: ${DB_DB}
      DB_TYPE: postgresql+psycopg2
      SECRET: ${SECRET}
      COUNT_IN_YEAR: ${COUNT_IN_YEAR}
    
    volumes:
      - ./web:/app:ro
    
    depends_on:
      - db
    
  nginx:
    image: nginx:1-alpine
    ports:
      - 8003:80
    volumes:
      - ./nginx/html/:/var/www/html
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    
    depends_on:
      - web

 
  adminer:
    image: adminer

    depends_on:
      - db
