create table articles
(
    id         integer generated by default as identity
        constraint articles_pk
            primary key,
    name       varchar               not null,
    list_id    integer               not null
        constraint articles_list_id_fk
            references list,
    barcode    char(12),
    imported   boolean default false not null,
    invoice_id integer
        constraint articles_invoices_id_fk
            references invoice,
    deleted    boolean default false not null,
    size       varchar(10),
    price      numeric               not null,
    id_in_list integer               not null
);

alter table articles
    owner to ksb;

create index articles_barcode_index
    on articles (barcode);

