create table users
(
    id           integer generated by default as identity
        constraint users_pk
            primary key,
    first_name   varchar     not null,
    last_name    varchar     not null,
    email        varchar     not null,
    password     varchar     not null,
    nickname     varchar     not null,
    clearance    integer default 10,
    address      varchar(50) not null,
    phone_number varchar(20) not null
);

alter table users
    owner to ksb;


create table list
(
    id         integer generated by default as identity
        constraint list_pk
            primary key,
    owner_id   integer not null
        constraint list_users_id_fk
            references users,
    id_in_user integer not null
);

alter table list
    owner to ksb;

create table invoice
(
    id            integer generated by default as identity
        constraint invoices_pk
            primary key,
    creation_time timestamp default clock_timestamp() not null
);

alter table invoice
    owner to ksb;

create sequence invoices_id_seq;

alter sequence invoices_id_seq owner to ksb;

alter sequence invoices_id_seq owned by invoice.id;

create table articles
(
    id         integer generated by default as identity
        constraint articles_pk
            primary key,
    name       varchar               not null,
    list_id    integer               not null
        constraint articles_list_id_fk
            references list,
    barcode    char(12),
    imported   boolean default false not null,
    invoice_id integer
        constraint articles_invoices_id_fk
            references invoice,
    deleted    boolean default false not null,
    size       varchar(10),
    price      numeric               not null,
    id_in_list integer               not null
);

alter table articles
    owner to ksb;

create index articles_barcode_index
    on articles (barcode);