create table invoice
(
    id            integer generated by default as identity
        constraint invoices_pk
            primary key,
    creation_time timestamp default clock_timestamp() not null
);

alter table invoice
    owner to ksb;

