create table list
(
    id         integer generated by default as identity
        constraint list_pk
            primary key,
    owner_id   integer not null
        constraint list_users_id_fk
            references users,
    id_in_user integer not null
);

alter table list
    owner to ksb;

